"""Generate images with multi-key provider failover: Gemini <-> OpenRouter."""
from __future__ import annotations

import base64
import io
import json
import re
from pathlib import Path
from typing import Any, Dict

import requests
from PIL import Image

from config.settings import settings


OPENROUTER_IMAGES_URL = "https://openrouter.ai/api/v1/images"
GEMINI_INTERACTIONS_URL = "https://generativelanguage.googleapis.com/v1beta/interactions"


def _keys(raw: str, extras: list[str]) -> list[str]:
    values: list[str] = []
    for item in [raw, *extras]:
        for key in item.split(","):
            key = key.strip()
            if key and key not in values:
                values.append(key)
    return values


def _redact(text: str) -> str:
    """Never expose API keys or authorization material in UI/log errors."""
    text = str(text)
    patterns = [
        r"(sk-or-v1-[A-Za-z0-9_-]+)",
        r"(AIza[A-Za-z0-9_-]+)",
        r"(Bearer\s+)[A-Za-z0-9._~+/=-]+",
        r'''(x-goog-api-key["']?\s*[:=]\s*["']?)[^\s,"'}]+''',
        r'''(api[_-]?key["']?\s*[:=]\s*["']?)[^\s,"'}]+''',
    ]
    for pattern in patterns:
        text = re.sub(
            pattern,
            lambda m: (m.group(1) if m.lastindex else "") + "[REDACTED]",
            text,
            flags=re.IGNORECASE,
        )
    return text[:1800]


def _build_prompt(prompt_data: Dict[str, Any]) -> str:
    parts = [
        prompt_data.get("subject", ""),
        ", ".join(prompt_data.get("artform", [])),
        (
            f"shot with {prompt_data.get('device', ['camera'])[0]}"
            if prompt_data.get("device")
            else ""
        ),
        "style: " + ", ".join(prompt_data.get("photography_style", [])),
    ]
    scene = prompt_data.get("scene_details", {})
    if scene.get("lighting"):
        parts.append("lighting: " + ", ".join(scene["lighting"]))
    if scene.get("composition"):
        parts.append("composition: " + ", ".join(scene["composition"]))
    parts.append(
        prompt_data.get(
            "additional_details",
            "vertical 9:16 composition, high quality, no text, no watermark",
        )
    )
    parts.append(
        "Create a single vertical 9:16 image suitable for a short-form video. "
        "Do not add text, logos, captions, borders, or watermarks."
    )
    return ", ".join(p for p in parts if p)


def _extract_openrouter_image_bytes(result: Dict[str, Any]) -> bytes:
    data = result.get("data")
    if not isinstance(data, list) or not data:
        raise RuntimeError("OpenRouter returned no image data.")

    first = data[0]
    if not isinstance(first, dict):
        raise RuntimeError("OpenRouter returned an invalid image item.")

    b64 = first.get("b64_json") or first.get("b64Json")
    if b64:
        return base64.b64decode(b64)

    image_url = first.get("url")
    if image_url:
        response = requests.get(image_url, timeout=60)
        response.raise_for_status()
        return response.content

    raise RuntimeError("OpenRouter response contained neither image data nor URL.")


def _extract_gemini_image_bytes(result: Dict[str, Any]) -> bytes:
    output_image = result.get("output_image")
    if isinstance(output_image, dict) and output_image.get("data"):
        return base64.b64decode(output_image["data"])

    for step in result.get("steps", []) or []:
        for block in step.get("content", []) or []:
            if (
                isinstance(block, dict)
                and block.get("type") == "image"
                and block.get("data")
            ):
                return base64.b64decode(block["data"])

    raise RuntimeError("Gemini returned no image data.")


def _normalize_to_png(image_bytes: bytes, image_path: Path) -> None:
    try:
        with Image.open(io.BytesIO(image_bytes)) as image:
            image.convert("RGB").save(image_path, format="PNG")
    except Exception as exc:
        raise RuntimeError(f"Generated bytes are not a valid image: {exc}") from exc


def _generate_openrouter(prompt_text: str, api_key: str) -> bytes:
    response = requests.post(
        OPENROUTER_IMAGES_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.OPENROUTER_IMAGE_MODEL,
            "prompt": prompt_text,
            "aspect_ratio": settings.OPENROUTER_IMAGE_ASPECT_RATIO,
            "n": 1,
        },
        timeout=180,
    )
    if response.status_code != 200:
        raise RuntimeError(
            f"OpenRouter HTTP {response.status_code}: "
            f"{_redact(response.text)}"
        )
    try:
        result = response.json()
    except ValueError as exc:
        raise RuntimeError("OpenRouter returned invalid JSON.") from exc
    return _extract_openrouter_image_bytes(result)


def _generate_gemini(prompt_text: str, api_key: str) -> bytes:
    response = requests.post(
        GEMINI_INTERACTIONS_URL,
        headers={
            "x-goog-api-key": api_key,
            "Content-Type": "application/json",
        },
        json={
            "model": settings.GEMINI_IMAGE_MODEL,
            "input": prompt_text,
            "response_format": {
                "type": "image",
                "mime_type": "image/png",
                "aspect_ratio": settings.GEMINI_IMAGE_ASPECT_RATIO,
                "image_size": settings.GEMINI_IMAGE_SIZE,
            },
        },
        timeout=180,
    )
    if response.status_code != 200:
        raise RuntimeError(
            f"Gemini HTTP {response.status_code}: "
            f"{_redact(response.text)}"
        )
    try:
        result = response.json()
    except ValueError as exc:
        raise RuntimeError("Gemini returned invalid JSON.") from exc
    return _extract_gemini_image_bytes(result)


def generate_images(image_prompts_path: Path, output_dir: Path) -> None:
    with open(image_prompts_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prompts = data.get("prompts", [])
    if not prompts:
        raise ValueError("No prompts found in image_prompts.json.")

    output_dir.mkdir(parents=True, exist_ok=True)
    for old in output_dir.iterdir():
        if old.is_file() and old.suffix.lower() in {".jpeg", ".jpg", ".png", ".webp"}:
            old.unlink()

    providers = settings.image_provider_order()
    provider_keys = {
        "gemini": _keys(settings.GEMINI_API_KEY, settings.GEMINI_API_KEYS),
        "openrouter": _keys(
            settings.OPENROUTER_API_KEY, settings.OPENROUTER_API_KEYS
        ),
    }

    available = [
        p for p in providers
        if p in provider_keys and provider_keys[p]
    ]
    if not available:
        raise RuntimeError(
            "No image provider API key is configured. "
            "Set GEMINI_API_KEY/GEMINI_API_KEYS or "
            "OPENROUTER_API_KEY/OPENROUTER_API_KEYS."
        )

    generated = 0
    # Permanent authentication/credit failures should not be retried for every scene.
    # Transient failures (including rate limits) remain eligible for the next scene.
    disabled_keys: set[tuple[str, int]] = set()

    for i, prompt_data in enumerate(prompts, start=1):
        prompt_text = _build_prompt(prompt_data)
        saved = False
        errors: list[str] = []

        for provider in available:
            keys = provider_keys[provider]
            for key_index, api_key in enumerate(keys, start=1):
                if (provider, key_index) in disabled_keys:
                    continue
                try:
                    print(
                        f"Generating image {i}/{len(prompts)} with "
                        f"{provider} key #{key_index}..."
                    )
                    if provider == "gemini":
                        image_bytes = _generate_gemini(prompt_text, api_key)
                    else:
                        image_bytes = _generate_openrouter(prompt_text, api_key)

                    image_path = output_dir / f"{i:03d}.png"
                    _normalize_to_png(image_bytes, image_path)
                    if image_path.stat().st_size == 0:
                        raise RuntimeError("generated image is empty")

                    print(f"Saved {image_path} via {provider} key #{key_index}")
                    generated += 1
                    saved = True
                    break
                except Exception as exc:
                    safe_error = _redact(str(exc))
                    errors.append(
                        f"{provider} key #{key_index}: {safe_error}"
                    )
                    # 401/402/403/404 generally indicate a key/account/model
                    # configuration problem. Do not burn the same key on every scene.
                    match = re.search(r"HTTP\s+(401|402|403|404)\b", safe_error)
                    if match:
                        disabled_keys.add((provider, key_index))
                    print(
                        f"{provider} key #{key_index} failed for image {i}; "
                        "trying the next key/provider."
                    )
            if saved:
                break

        if not saved:
            active = sum(1 for p in available for k in provider_keys[p] if (p, provider_keys[p].index(k) + 1) not in disabled_keys)
            summary = " | ".join(errors)
            raise RuntimeError(
                f"Image {i}/{len(prompts)} failed. "
                f"All currently usable image keys/providers were tried. "
                f"Active fallback keys remaining: {active}. "
                f"Details: {summary}"
            )

    if generated != len(prompts):
        raise RuntimeError(
            f"Image generation incomplete: created {generated} of "
            f"{len(prompts)} required images."
        )
