"""Generate images with ordered provider failover: OpenRouter -> Gemini."""
from __future__ import annotations

import base64
import io
import json
from pathlib import Path
from typing import Any, Dict

import requests
from PIL import Image

from config.settings import settings


OPENROUTER_IMAGES_URL = "https://openrouter.ai/api/v1/images"
GEMINI_INTERACTIONS_URL = "https://generativelanguage.googleapis.com/v1beta/interactions"


def _build_prompt(prompt_data: Dict[str, Any]) -> str:
    parts = [
        prompt_data.get("subject", ""),
        ", ".join(prompt_data.get("artform", [])),
        (
            f"shot with {prompt_data.get('device', ['camera'])[0]}"
            if prompt_data.get("device")
            else ""
        ),
        "style: " + ", ".join(prompt_data.get("photography_style", [])),
    ]
    scene = prompt_data.get("scene_details", {})
    if scene.get("lighting"):
        parts.append("lighting: " + ", ".join(scene["lighting"]))
    if scene.get("composition"):
        parts.append("composition: " + ", ".join(scene["composition"]))
    parts.append(
        prompt_data.get(
            "additional_details",
            "vertical 9:16 composition, high quality, no text, no watermark",
        )
    )
    parts.append(
        "Create a single vertical 9:16 image suitable for a short-form video. "
        "Do not add text, logos, captions, borders, or watermarks."
    )
    return ", ".join(p for p in parts if p)


def _extract_openrouter_image_bytes(result: Dict[str, Any]) -> bytes:
    data = result.get("data")
    if not isinstance(data, list) or not data:
        raise RuntimeError(
            "OpenRouter returned no image data: "
            f"{json.dumps(result)[:1600]}"
        )

    first = data[0]
    if not isinstance(first, dict):
        raise RuntimeError(f"OpenRouter returned an invalid image item: {first!r}")

    b64 = first.get("b64_json") or first.get("b64Json")
    if b64:
        return base64.b64decode(b64)

    image_url = first.get("url")
    if image_url:
        response = requests.get(image_url, timeout=60)
        response.raise_for_status()
        return response.content

    raise RuntimeError(
        "OpenRouter image response contained neither b64_json nor url: "
        f"{json.dumps(first)[:1000]}"
    )


def _extract_gemini_image_bytes(result: Dict[str, Any]) -> bytes:
    output_image = result.get("output_image")
    if isinstance(output_image, dict) and output_image.get("data"):
        return base64.b64decode(output_image["data"])

    for step in result.get("steps", []) or []:
        for block in step.get("content", []) or []:
            if (
                isinstance(block, dict)
                and block.get("type") == "image"
                and block.get("data")
            ):
                return base64.b64decode(block["data"])

    raise RuntimeError(
        "Gemini returned no image data: "
        f"{json.dumps(result)[:1600]}"
    )


def _normalize_to_png(image_bytes: bytes, image_path: Path) -> None:
    try:
        with Image.open(io.BytesIO(image_bytes)) as image:
            image.convert("RGB").save(image_path, format="PNG")
    except Exception as exc:
        raise RuntimeError(f"Generated bytes are not a valid image: {exc}") from exc


def _generate_openrouter(prompt_text: str) -> bytes:
    response = requests.post(
        OPENROUTER_IMAGES_URL,
        headers={
            "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": settings.OPENROUTER_IMAGE_MODEL,
            "prompt": prompt_text,
            "aspect_ratio": settings.OPENROUTER_IMAGE_ASPECT_RATIO,
            "n": 1,
        },
        timeout=180,
    )

    if response.status_code != 200:
        detail = response.text[:1600].replace("\n", " ")
        raise RuntimeError(
            f"OpenRouter HTTP {response.status_code} "
            f"using {settings.OPENROUTER_IMAGE_MODEL}: {detail}"
        )

    try:
        result = response.json()
    except ValueError as exc:
        raise RuntimeError(
            f"OpenRouter returned invalid JSON: {response.text[:800]}"
        ) from exc

    return _extract_openrouter_image_bytes(result)


def _generate_gemini(prompt_text: str) -> bytes:
    response = requests.post(
        GEMINI_INTERACTIONS_URL,
        headers={
            "x-goog-api-key": settings.GEMINI_API_KEY,
            "Content-Type": "application/json",
        },
        json={
            "model": settings.GEMINI_IMAGE_MODEL,
            "input": prompt_text,
            "response_format": {
                "type": "image",
                "mime_type": "image/png",
                "aspect_ratio": settings.GEMINI_IMAGE_ASPECT_RATIO,
                "image_size": settings.GEMINI_IMAGE_SIZE,
            },
        },
        timeout=180,
    )

    if response.status_code != 200:
        detail = response.text[:1600].replace("\n", " ")
        raise RuntimeError(
            f"Gemini HTTP {response.status_code} "
            f"using {settings.GEMINI_IMAGE_MODEL}: {detail}"
        )

    try:
        result = response.json()
    except ValueError as exc:
        raise RuntimeError(
            f"Gemini returned invalid JSON: {response.text[:800]}"
        ) from exc

    return _extract_gemini_image_bytes(result)


def generate_images(image_prompts_path: Path, output_dir: Path) -> None:
    """
    Generate one image per prompt.
    Provider order is controlled by IMAGE_PROVIDER_ORDER.
    When a provider fails, it is disabled for the remainder of the job and
    the next configured provider is used automatically.
    """
    with open(image_prompts_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prompts = data.get("prompts", [])
    if not prompts:
        raise ValueError("No prompts found in image_prompts.json.")

    output_dir.mkdir(parents=True, exist_ok=True)

    for old in output_dir.iterdir():
        if old.is_file() and old.suffix.lower() in {".jpeg", ".jpg", ".png", ".webp"}:
            old.unlink()

    provider_order = settings.image_provider_order()
    provider_failures: set[str] = set()
    providers_seen = set(provider_order)
    generated = 0

    for i, prompt_data in enumerate(prompts, start=1):
        prompt_text = _build_prompt(prompt_data)
        saved = False
        errors: list[str] = []

        for provider in provider_order:
            if provider in provider_failures:
                continue

            if provider == "openrouter" and not settings.OPENROUTER_API_KEY:
                errors.append("openrouter: API key not configured")
                continue
            if provider == "gemini" and not settings.GEMINI_API_KEY:
                errors.append("gemini: API key not configured")
                continue
            if provider not in {"openrouter", "gemini"}:
                provider_failures.add(provider)
                errors.append(f"{provider}: unsupported provider")
                continue

            try:
                print(
                    f"Generating image {i}/{len(prompts)} with {provider}..."
                )
                if provider == "openrouter":
                    image_bytes = _generate_openrouter(prompt_text)
                else:
                    image_bytes = _generate_gemini(prompt_text)

                image_path = output_dir / f"{i:03d}.png"
                _normalize_to_png(image_bytes, image_path)

                if image_path.stat().st_size == 0:
                    raise RuntimeError("generated image is empty")

                print(f"Saved {image_path} via {provider}")
                generated += 1
                saved = True
                break
            except Exception as exc:
                message = str(exc)
                provider_failures.add(provider)
                errors.append(f"{provider}: {message}")
                print(
                    f"Provider {provider} failed for image {i}; "
                    "trying next configured provider."
                )

        if not saved:
            configured = [
                p for p in provider_order
                if p in providers_seen
            ]
            raise RuntimeError(
                f"Image {i}/{len(prompts)} failed on all configured providers. "
                f"Order={configured}. "
                f"Details: {' | '.join(errors)}"
            )

    if generated != len(prompts):
        raise RuntimeError(
            f"Image generation incomplete: created {generated} of "
            f"{len(prompts)} required images."
        )
